name: flutter_spinbox
description: SpinBox for Flutter.
version: 0.1.0
homepage: https://github.com/jpnurmi/flutter_spinbox
repository: https://github.com/jpnurmi/flutter_spinbox
issue_tracker: https://github.com/jpnurmi/flutter_spinbox/issues

environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_test_ui: ^1.0.0
